version: "3.5"
services:
#  mysql:
#    #image: mysql:5.7
#    build: mysql/
#    container_name: cmysql-taller1
#    environment:
#      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#      MYSQL_DATABASE: taller1
#      MYSQL_USER: utaller1
#      MYSQL_PASSWORD_FILE: /run/secrets/db_password
#    volumes:
#      - mysql_data:/var/lib/mysql
#      #- ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
#    networks:
#      - back_net
#    ports:
#      - "3306:3306"
#    secrets:
#      - db_password

  backend:
    build: backend/
    networks:
      - back_net
#    depends_on:
#      - mysql

  frontend:
    build: frontend/
    networks:
      - front_net
    depends_on:
      - backend


#https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg
#https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

  balanceproxy:
    build: balanceproxy/
    container_name: cbp-taller1
    networks:
      - back_net
      - front_net
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend


volumes:
  mysql_data:
#  logs_data:


networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge


secrets:
  db_password:
    file: db_password.txt

