version: "3.5"
services: 
  mysql:
    #image: mysql:5.7
    build: mysql/
    container_name: mysql-taller1
    hostname: host-mysql-taller1
    environment:
      #MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: taller1
      MYSQL_USER: utaller1
      MYSQL_PASSWORD: ptaller1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back_net
    ports:
      - "3306:3306"

  backend:
    build: backend/
    networks:
      - back_net
    ports:
     - "8080:8080"    
    depends_on:
     - mysql

volumes:
  mysql_data:
 
networks:
  back_net:
    driver: bridge

